// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repository

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Author struct {
	ID             uuid.UUID        `json:"id"`
	Name           string           `json:"name"`
	Bio            pgtype.Text      `json:"bio"`
	OpenlibraryKey pgtype.Text      `json:"openlibrary_key"`
	Photos         []byte           `json:"photos"`
	AlternateNames []byte           `json:"alternate_names"`
	PersonalName   pgtype.Text      `json:"personal_name"`
	Links          []byte           `json:"links"`
	BirthDate      pgtype.Date      `json:"birth_date"`
	DeathDate      pgtype.Date      `json:"death_date"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
}

type Book struct {
	ID              uuid.UUID        `json:"id"`
	Isbn10          pgtype.Text      `json:"isbn_10"`
	Isbn13          pgtype.Text      `json:"isbn_13"`
	Title           string           `json:"title"`
	Publisher       pgtype.Text      `json:"publisher"`
	PublishedDate   pgtype.Text      `json:"published_date"`
	Description     pgtype.Text      `json:"description"`
	PageCount       pgtype.Int4      `json:"page_count"`
	Language        pgtype.Text      `json:"language"`
	ThumbnailUrl    pgtype.Text      `json:"thumbnail_url"`
	TotalCopies     int32            `json:"total_copies"`
	AvailableCopies int32            `json:"available_copies"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
}

type BookAuthor struct {
	BookID   uuid.UUID `json:"book_id"`
	AuthorID uuid.UUID `json:"author_id"`
}

type BookCategory struct {
	BookID     uuid.UUID `json:"book_id"`
	CategoryID uuid.UUID `json:"category_id"`
}

type BookReview struct {
	ID         uuid.UUID        `json:"id"`
	BookID     uuid.UUID        `json:"book_id"`
	UserID     uuid.UUID        `json:"user_id"`
	Rating     int32            `json:"rating"`
	ReviewText pgtype.Text      `json:"review_text"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
}

type Category struct {
	ID        uuid.UUID        `json:"id"`
	Name      string           `json:"name"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type Loan struct {
	ID           uuid.UUID        `json:"id"`
	UserID       uuid.UUID        `json:"user_id"`
	BookID       uuid.UUID        `json:"book_id"`
	BorrowedDate pgtype.Date      `json:"borrowed_date"`
	DueDate      pgtype.Date      `json:"due_date"`
	ReturnedDate pgtype.Date      `json:"returned_date"`
	Status       string           `json:"status"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

type User struct {
	ID           uuid.UUID        `json:"id"`
	Username     string           `json:"username"`
	Email        string           `json:"email"`
	PasswordHash string           `json:"password_hash"`
	Role         string           `json:"role"`
	FirstName    string           `json:"first_name"`
	LastName     string           `json:"last_name"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}
